### ISSUE TITLE
EPIC: Multiplier points calculation

### ISSUE THREAD

**Issue by 0x-r4bbit** [logos-co/staking#100]
This epic summarises issues and tasks related to the multiplier points calculation.
We'll close this once all related issues are closed.

- [x] https://github.com/logos-co/staking/issues/48
- [ ] https://github.com/logos-co/staking/issues/98
- [x] https://github.com/logos-co/staking/issues/99
